Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/flo/source/github.com/florian42/url-shortener/lambda
      Runtime: python3.9